[tool.pytest.ini_options]
addopts = "--strict-markers --cov aiostream"

[tool.pyright]
ignore = ["aiostream/test_utils.py"]

[tool.black]
line-length = 80
target_version = ["py38", "py39", "py310", "py311", "py312"]

[tool.mypy]
strict = true
packages = ["aiostream", "examples"]
